// This file is generated by scripts/sync-content.mjs. Do not edit by hand.

export const notebookModules = {
  "/basis/01_grad_descent_details_visualization.ipynb": () => import("/basis/01_grad_descent_details_visualization.ipynb?raw").then((module) => module.default),
  "/basis/02_pytorch_mle_for_bernoulli.ipynb": () => import("/basis/02_pytorch_mle_for_bernoulli.ipynb?raw").then((module) => module.default),
  "/basis/derivative_partial_directional.ipynb": () => import("/basis/derivative_partial_directional.ipynb?raw").then((module) => module.default),
  "/math/convex_function_jensen_inequality.ipynb": () => import("/math/convex_function_jensen_inequality.ipynb?raw").then((module) => module.default),
  "/math/matrix/Lp_norm_matrix_norm.ipynb": () => import("/math/matrix/Lp_norm_matrix_norm.ipynb?raw").then((module) => module.default),
  "/math/matrix/rotation matrix.ipynb": () => import("/math/matrix/rotation matrix.ipynb?raw").then((module) => module.default),
  "/math/matrix/spectral_norm.ipynb": () => import("/math/matrix/spectral_norm.ipynb?raw").then((module) => module.default),
  "/math/prob_stats/forward_reverse_kl_div.ipynb": () => import("/math/prob_stats/forward_reverse_kl_div.ipynb?raw").then((module) => module.default),
  "/math/prob_stats/kl_div_basics.ipynb": () => import("/math/prob_stats/kl_div_basics.ipynb?raw").then((module) => module.default),
  "/math/prob_stats/pytorch_kl_div_examples.ipynb": () => import("/math/prob_stats/pytorch_kl_div_examples.ipynb?raw").then((module) => module.default),
  "/optimizer/adadelta_adam.ipynb": () => import("/optimizer/adadelta_adam.ipynb?raw").then((module) => module.default),
  "/optimizer/adagrad_rmsprop.ipynb": () => import("/optimizer/adagrad_rmsprop.ipynb?raw").then((module) => module.default),
  "/optimizer/l2_reg_weight_decay_adaw.ipynb": () => import("/optimizer/l2_reg_weight_decay_adaw.ipynb?raw").then((module) => module.default),
  "/optimizer/lr_scheduler.ipynb": () => import("/optimizer/lr_scheduler.ipynb?raw").then((module) => module.default),
  "/optimizer/pytorch_as_a_general_optimizer.ipynb": () => import("/optimizer/pytorch_as_a_general_optimizer.ipynb?raw").then((module) => module.default),
}
