// This file is generated by scripts/sync-content.mjs. Do not edit by hand.

export const generatedSidebar = [
  {
    text: "Basics",
    collapsed: false,
    items: [
      {
        text: "Micrograd",
        link: "/basis/micrograd"
      },
      {
        text: "XGBoost",
        link: "/basis/xgboost"
      },
      {
        text: "Gradient Descent Details Visualization",
        link: "/basis/_notebooks/grad-descent-details-visualization"
      },
      {
        text: "PyTorch MLE for Bernoulli",
        link: "/basis/_notebooks/pytorch-mle-for-bernoulli"
      },
      {
        text: "Derivative Partial Directional",
        link: "/basis/_notebooks/derivative-partial-directional"
      }
    ]
  },
  {
    text: "Math",
    collapsed: false,
    items: [
      {
        text: "Convex Function Jensen Inequality",
        link: "/math/_notebooks/convex-function-jensen-inequality"
      },
      {
        text: "Matrix",
        collapsed: false,
        items: [
          {
            text: "Lp Norm Matrix Norm",
            link: "/math/matrix/_notebooks/lp-norm-matrix-norm"
          },
          {
            text: "Spectral Norm",
            link: "/math/matrix/_notebooks/spectral-norm"
          },
          {
            text: "Rotation Matrix",
            link: "/math/matrix/_notebooks/rotation-matrix"
          }
        ]
      },
      {
        text: "Probability & Stats",
        collapsed: false,
        items: [
          {
            text: "Forward Reverse KL Div",
            link: "/math/prob_stats/_notebooks/forward-reverse-kl-div"
          },
          {
            text: "KL Div Basics",
            link: "/math/prob_stats/_notebooks/kl-div-basics"
          },
          {
            text: "PyTorch KL Div Examples",
            link: "/math/prob_stats/_notebooks/pytorch-kl-div-examples"
          }
        ]
      }
    ]
  },
  {
    text: "Roadmap",
    collapsed: false,
    items: [
      {
        text: "LLM Roadmap",
        link: "/roadmap/roadmap"
      },
      {
        text: "LLM Study Plan",
        link: "/roadmap/studyplan"
      },
      {
        text: "Suggestions",
        collapsed: false,
        items: [
          {
            text: "modern_ai_for_beginners",
            link: "/roadmap/suggestions/modern_ai_for_beginners"
          },
          {
            text: "How to learn LLM",
            link: "/roadmap/suggestions/how_to_learn_llm"
          },
          {
            text: "How to learn RL",
            link: "/roadmap/suggestions/how_to_learn_rl"
          },
          {
            text: "modern_genai_bilibili",
            link: "/roadmap/suggestions/modern_genai"
          }
        ]
      }
    ]
  },
  {
    text: "Optimizers",
    collapsed: false,
    items: [
      {
        text: "Optimizers",
        link: "/optimizer/"
      },
      {
        text: "LR Scheduler",
        link: "/optimizer/_notebooks/lr-scheduler"
      },
      {
        text: "AdaGrad RMSProp",
        link: "/optimizer/_notebooks/adagrad-rmsprop"
      },
      {
        text: "AdaDelta Adam",
        link: "/optimizer/_notebooks/adadelta-adam"
      },
      {
        text: "L2, Weight Decay, AdamW",
        link: "/optimizer/_notebooks/l2-reg-weight-decay-adamw"
      },
      {
        text: "PyTorch as General Optimizer",
        link: "/optimizer/_notebooks/pytorch-as-general-optimizer"
      }
    ]
  }
]
