import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()
const generatedSidebarPath = path.join(root, '.vitepress', 'sidebar.generated.ts')
const generatedNotebooksPath = path.join(root, '.vitepress', 'notebooks.generated.ts')
const generatedNotebookDir = '_notebooks'
const preferredRootOrder = ['basis', 'math', 'roadmap', 'optimizer']
const ignoredTopLevelDirs = new Set([
  '.agents',
  '.codex',
  '.git',
  '.github',
  '.venv',
  '.vitepress',
  'images',
  'node_modules',
  'scripts',
])

const folderTitles = {
  basis: 'Basics',
  math: 'Math',
  roadmap: 'Roadmap',
  optimizer: 'Optimizers',
  matrix: 'Matrix',
  prob_stats: 'Probability & Stats',
}

const preferredOrder = [
  'basis/micrograd.md',
  'basis/xgboost.md',
  'basis/grad-descent-details-visualization.md',
  'basis/pytorch-mle-for-bernoulli.md',
  'basis/derivative-partial-directional.md',
  'math/convex-function-jensen-inequality.md',
  'math/matrix/lp-norm-matrix-norm.md',
  'math/matrix/spectral-norm.md',
  'math/matrix/rotation-matrix.md',
  'math/prob_stats/forward-reverse-kl-div.md',
  'math/prob_stats/kl-div-basics.md',
  'math/prob_stats/pytorch-kl-div-examples.md',
  'roadmap/roadmap.md',
  'roadmap/studyplan.md',
  'roadmap/suggestions/llm_link.md',
  'roadmap/suggestions/modern_ai_for_beginners.md',
  'roadmap/suggestions/how_to_learn_llm.md',
  'roadmap/suggestions/how_to_learn_rl.md',
  'optimizer/index.md',
  'optimizer/lr-scheduler.md',
  'optimizer/adagrad-rmsprop.md',
  'optimizer/adadelta-adam.md',
  'optimizer/l2-reg-weight-decay-adamw.md',
  'optimizer/pytorch-as-general-optimizer.md',
]

const notebookPlacementOverrides = {
  'basis/01_grad_descent_details_visualization.ipynb': 'basis/grad-descent-details-visualization.md',
  'basis/02_pytorch_mle_for_bernoulli.ipynb': 'basis/pytorch-mle-for-bernoulli.md',
  'optimizer/l2_reg_weight_decay_adaw.ipynb': 'optimizer/l2-reg-weight-decay-adamw.md',
  'optimizer/pytorch_as_a_general_optimizer.ipynb': 'optimizer/pytorch-as-general-optimizer.md',
}

const notebookTitleOverrides = {
  'basis/01_grad_descent_details_visualization.ipynb': 'Gradient Descent Details Visualization',
  'basis/02_pytorch_mle_for_bernoulli.ipynb': 'PyTorch MLE for Bernoulli',
  'optimizer/l2_reg_weight_decay_adaw.ipynb': 'L2, Weight Decay, AdamW',
  'optimizer/pytorch_as_a_general_optimizer.ipynb': 'PyTorch as General Optimizer',
}

const generatedNotebookMarker = '<!-- Generated by scripts/sync-content.mjs. Edit the source .ipynb instead. -->'

function isContentFile(filePath) {
  return filePath.endsWith('.md') || filePath.endsWith('.ipynb')
}

function toPosix(filePath) {
  return filePath.split(path.sep).join('/')
}

function slugify(value) {
  return value
    .replace(/\.ipynb$/i, '')
    .replace(/\.md$/i, '')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .replace(/[^a-zA-Z0-9/-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()
}

function titleFromSlug(value) {
  const title = value
    .replace(/\.ipynb$/i, '')
    .replace(/\.md$/i, '')
    .replace(/[_-]+/g, ' ')
    .replace(/^\d+\s+/, '')
    .replace(/\b\w/g, (letter) => letter.toUpperCase())

  return title
    .replace(/\bKl\b/g, 'KL')
    .replace(/\bMle\b/g, 'MLE')
    .replace(/\bLr\b/g, 'LR')
    .replace(/\bLp\b/g, 'Lp')
    .replace(/\bAi\b/g, 'AI')
    .replace(/\bLlm\b/g, 'LLM')
    .replace(/\bRl\b/g, 'RL')
    .replace(/\bPytorch\b/g, 'PyTorch')
    .replace(/\bRmsprop\b/g, 'RMSProp')
    .replace(/\bAdagrad\b/g, 'AdaGrad')
    .replace(/\bAdadelta\b/g, 'AdaDelta')
    .replace(/\bAdamw\b/g, 'AdamW')
    .replace(/\bXgboost\b/g, 'XGBoost')
    .replace(/\bElbo\b/g, 'ELBO')
}

function titleFromMarkdown(content, fallback) {
  const match = content.match(/^#\s+(.+)$/m)
  return match?.[1]?.trim() || fallback
}

function escapeVueAttribute(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = []

  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...await walk(fullPath))
    } else if (entry.isFile() && isContentFile(entry.name)) {
      files.push(fullPath)
    }
  }

  return files
}

async function detectContentRoots() {
  const entries = await readdir(root, { withFileTypes: true })
  const roots = []

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith('.') || ignoredTopLevelDirs.has(entry.name)) continue
    const files = await walk(path.join(root, entry.name))
    if (files.length) roots.push(entry.name)
  }

  return roots.sort((a, b) => {
    const rankA = preferredRootOrder.indexOf(a)
    const rankB = preferredRootOrder.indexOf(b)
    if (rankA !== -1 || rankB !== -1) {
      return (rankA === -1 ? 1000 : rankA) - (rankB === -1 ? 1000 : rankB)
    }
    return nodeTitle(createTreeNode(a)).localeCompare(nodeTitle(createTreeNode(b)))
  })
}

function notebookPlacementPath(ipynbRelativePath) {
  const parsed = path.parse(ipynbRelativePath)
  const slugName = slugify(parsed.base)
  return notebookPlacementOverrides[ipynbRelativePath] || toPosix(path.join(parsed.dir, `${slugName}.md`))
}

function notebookWrapperPath(ipynbRelativePath) {
  const placementPath = notebookPlacementPath(ipynbRelativePath)
  const parsed = path.parse(placementPath)
  return toPosix(path.join(parsed.dir, generatedNotebookDir, parsed.base))
}

async function ensureNotebookPage(ipynbRelativePath, title) {
  const parsed = path.parse(ipynbRelativePath)
  const slugName = slugify(parsed.base)
  let pageRelativePath = notebookWrapperPath(ipynbRelativePath)
  let pageFullPath = path.join(root, pageRelativePath)
  const content = `${generatedNotebookMarker}\n<NotebookViewer path="/${ipynbRelativePath}" title="${escapeVueAttribute(title)}" />\n`

  await mkdir(path.dirname(pageFullPath), { recursive: true })

  let existing = ''
  try {
    existing = await readFile(pageFullPath, 'utf8')
  } catch {
    // New generated page.
  }

  const isGeneratedPage = existing.includes(generatedNotebookMarker) || existing.trim().startsWith('<NotebookViewer')
  if (existing && existing !== content && !isGeneratedPage) {
    pageRelativePath = toPosix(path.join(parsed.dir, generatedNotebookDir, `${slugName}-notebook.md`))
    pageFullPath = path.join(root, pageRelativePath)
    existing = ''
    try {
      existing = await readFile(pageFullPath, 'utf8')
    } catch {
      // New generated page.
    }
  }

  if (existing !== content) {
    await writeFile(pageFullPath, content)
  }

  return pageRelativePath
}

async function removeStaleNotebookPages(contentRoots, expectedPages) {
  for (const contentRoot of contentRoots) {
    const files = await walk(path.join(root, contentRoot))

    for (const fullPath of files) {
      if (!fullPath.endsWith('.md')) continue
      const relativePath = toPosix(path.relative(root, fullPath))
      const content = await readFile(fullPath, 'utf8')

      if (content.includes(generatedNotebookMarker) && !expectedPages.has(relativePath)) {
        await unlink(fullPath)
      }
    }
  }
}

function createTreeNode(name, segmentPath = '') {
  return {
    name,
    segmentPath,
    pages: [],
    children: new Map(),
  }
}

function addPage(tree, relativePath, title, linkRelativePath = relativePath) {
  const parts = relativePath.split('/')
  parts.pop()
  let node = tree

  parts.forEach((part, index) => {
    if (!node.children.has(part)) {
      node.children.set(part, createTreeNode(part, parts.slice(0, index + 1).join('/')))
    }
    node = node.children.get(part)
  })

  if (node.pages.some((page) => page.relativePath === relativePath)) return

  node.pages.push({
    text: title,
    link: linkRelativePath.endsWith('/index.md') ? `/${linkRelativePath.replace(/\/index\.md$/i, '/')}` : `/${linkRelativePath.replace(/\.md$/i, '')}`,
    relativePath,
  })
}

function pageRank(relativePath) {
  const index = preferredOrder.indexOf(relativePath)
  if (index !== -1) return index
  if (relativePath.endsWith('/index.md')) return 0
  return 1000
}

function sortPages(pages) {
  return pages.sort((a, b) => {
    const rankDelta = pageRank(a.relativePath) - pageRank(b.relativePath)
    if (rankDelta !== 0) return rankDelta
    return a.text.localeCompare(b.text)
  })
}

function nodeTitle(node) {
  return folderTitles[node.name] || titleFromSlug(node.name)
}

function nodeToSidebar(node, isRootChild = false) {
  const items = [
    ...sortPages(node.pages).map(({ text, link }) => ({ text, link })),
    ...Array.from(node.children.values())
      .sort((a, b) => nodeTitle(a).localeCompare(nodeTitle(b)))
      .map((child) => nodeToSidebar(child)),
  ]

  return {
    text: isRootChild ? nodeTitle(node) : nodeTitle(node),
    collapsed: false,
    items,
  }
}

function formatSidebarValue(value, indent = 0) {
  const pad = '  '.repeat(indent)
  const nextPad = '  '.repeat(indent + 1)

  if (Array.isArray(value)) {
    if (!value.length) return '[]'
    return `[\n${value.map((item) => `${nextPad}${formatSidebarValue(item, indent + 1)}`).join(',\n')}\n${pad}]`
  }

  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value)
    return `{\n${entries.map(([key, item]) => `${nextPad}${key}: ${formatSidebarValue(item, indent + 1)}`).join(',\n')}\n${pad}}`
  }

  return JSON.stringify(value)
}

async function main() {
  const tree = createTreeNode('root')
  const contentRoots = await detectContentRoots()
  const notebookPaths = []
  const expectedNotebookPages = new Set()

  for (const contentRoot of contentRoots) {
    const fullRoot = path.join(root, contentRoot)
    const files = await walk(fullRoot)

    for (const fullPath of files) {
      const relativePath = toPosix(path.relative(root, fullPath))

      if (relativePath.endsWith('.ipynb')) {
        notebookPaths.push(relativePath)
        const title = notebookTitleOverrides[relativePath] || titleFromSlug(path.basename(relativePath))
        const pagePath = await ensureNotebookPage(relativePath, title)
        expectedNotebookPages.add(pagePath)
        addPage(
          tree,
          notebookPlacementPath(relativePath),
          title,
          pagePath,
        )
        continue
      }

      const content = await readFile(fullPath, 'utf8')
      if (content.includes(generatedNotebookMarker) || content.trim().startsWith('<NotebookViewer')) {
        continue
      }

      addPage(tree, relativePath, titleFromMarkdown(content, titleFromSlug(path.basename(relativePath))))
    }
  }

  await removeStaleNotebookPages(contentRoots, expectedNotebookPages)

  const sidebar = contentRoots
    .map((contentRoot) => tree.children.get(contentRoot))
    .filter(Boolean)
    .map((node) => nodeToSidebar(node, true))

  const fileContent = `// This file is generated by scripts/sync-content.mjs. Do not edit by hand.\n\nexport const generatedSidebar = ${formatSidebarValue(sidebar)}\n`
  await writeFile(generatedSidebarPath, fileContent)

  const notebookContent = [
    '// This file is generated by scripts/sync-content.mjs. Do not edit by hand.',
    '',
    'export const notebookModules = {',
    ...notebookPaths.sort().map((notebookPath) => `  "/${notebookPath}": () => import("/${notebookPath}?raw").then((module) => module.default),`),
    '}',
    '',
  ].join('\n')
  await writeFile(generatedNotebooksPath, notebookContent)
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
